### ISSUE TITLE
Crash of GeanyPy when disabling and enabling after loading faulty plugin

### ISSUE THREAD

**Issue by frlan** [codebrainz/geanypy#18] opened 2015-02-19 15:38 UTC
Writing faulty plugin, which cannot be loaded:
> /home/frlan/.config/geany/plugins/geanypy/plugins/geanypysql/geanypysql.py:46:
> GtkWarning: Main: missing action (null)
>  menu = uimanager.get_widget('/MenuBar/Main')
> Traceback (most recent call last):
>  File "/usr/local/lib/geany-plugins/geanypy/geany/manager.py", line 12, in __init__
>    self.loader = PluginLoader(plugin_dirs)
>  File "/usr/local/lib/geany-plugins/geanypy/geany/loader.py", line 21, in __init__
>    self.restore_loaded_plugins()
> File "/usr/local/lib/geany-plugins/geanypy/geany/loader.py", line 49, in restore_loaded_plugins
>    self.load_plugin(filename)
> File "/usr/local/lib/geany-plugins/geanypy/geany/loader.py", line 131, in load_plugin
>   inst = avail.cls()
>  File "/home/frlan/.config/geany/plugins/geanypy/plugins/geanypysql/geanypysql.py", line 47, in __init__ menu.show_all()
> AttributeError: 'NoneType' object has no attribute 'show_all'

Causing an error:
> (geany:6687): GeanyPy-WARNING **: Konnte keine neue Instanz der Plugin-Verwaltung anlegen.

(Could not create a new instance of Plugin Manager)

> Geany-INFO: Loaded:   /usr/local/lib/geany/geanypy.so (GeanyPy)[Thread 0x7fff7e5bb700 (LWP 6727) exited]

> (geany:6687): GeanyPy-CRITICAL **: GeanyPy_show_manager: assertion 'manager != NULL' failed

Now unloading GeanyPy and try to reenable it:

> #0  0x00007fff6a025c90 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #1  0x00007fff6a04bc92 in PyType_Ready () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #2  0x00007fff6a04e5ce in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #3  0x00007fff6a048ce3 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #4  0x00007fff6a0d0be3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #5  0x00007fff6a0d0fdf in PyObject_CallFunctionObjArgs () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #6  0x00007fff6a102fcd in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #7  0x00007fff6a179190 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #8  0x00007fff6a100639 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #9  0x00007fff6a13a7b9 in PyImport_ExecCodeModuleEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #10 0x00007fff6a13b90e in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #11 0x00007fff6a076e81 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #12 0x00007fff6a07746d in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #13 0x00007fff6a10c468 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #14 0x00007fff6a0d0be3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #15 0x00007fff6a1786e7 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #16 0x00007fff6a101f02 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #17 0x00007fff6a179190 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #18 0x00007fff6a100639 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #19 0x00007fff6a13a7b9 in PyImport_ExecCodeModuleEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #20 0x00007fff6a13b90e in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #21 0x00007fff6a076e81 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #22 0x00007fff6a07746d in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #23 0x00007fff6a10c468 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #24 0x00007fff6a0d0be3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #25 0x00007fff6a1786e7 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #26 0x00007fff6a101f02 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #27 0x00007fff6a179190 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #28 0x00007fff6a100639 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #29 0x00007fff6a13a7b9 in PyImport_ExecCodeModuleEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #30 0x00007fff6a13b90e in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #31 0x00007fff6a076e81 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #32 0x00007fff6a07746d in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #33 0x00007fff6a10c468 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #34 0x00007fff6a0d0be3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #35 0x00007fff6a1786e7 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #36 0x00007fff6a101f02 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #37 0x00007fff6a179190 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> ---Type <return> to continue, or q <return> to quit---
> #38 0x00007fff6a100639 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #39 0x00007fff6a13a7b9 in PyImport_ExecCodeModuleEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #40 0x00007fff6a13b90e in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #41 0x00007fff6a076e81 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #42 0x00007fff6a07746d in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #43 0x00007fff6a10c468 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #44 0x00007fff6a0d0be3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #45 0x00007fff6a0d1be1 in PyObject_CallFunction () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #46 0x00007fff6a077ea6 in PyImport_Import () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #47 0x00007fff6a07804a in PyImport_ImportModule () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #48 0x00007fff6a12000c in Py_InitializeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
> #49 0x00007fff69d7985f in GeanyPy_start_interpreter () at ../geanypy/src/geanypy-plugin.c:88
> #50 plugin_init (data=<optimized out>) at ../geanypy/src/geanypy-plugin.c:249
> #51 0x00000000004c33d1 in plugin_load (plugin=0x16b1190) at ../src/plugins.c:614
> #52 plugin_new (fname=0x1a1e650 "/usr/local/lib/geany/geanypy.so", load_plugin=1, add_to_list=1) at ../src/plugins.c:769
> #53 0x00000000004c3f8f in pm_plugin_toggled (cell=0x7fff63dad998, pth=0x88 <error: Cannot access memory at address 0x88>, data=0x0)
>     at ../src/plugins.c:1281
> #54 0x00007ffff6151ed0 in g_cclosure_marshal_VOID__STRINGv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #55 0x00007ffff614f474 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #56 0x00007ffff6169087 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #57 0x00007ffff61699df in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #58 0x00007ffff782c711 in gtk_cell_renderer_toggle_activate (cell=<optimized out>, event=<optimized out>, widget=<optimized out>, 
>     path=<optimized out>, background_area=<optimized out>, cell_area=<optimized out>, flags=(unknown: 0))
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkcellrenderertoggle.c:407
> #59 0x00007ffff79ca477 in gtk_tree_view_column_cell_process_action (tree_column=0x11, window=0x88, window@entry=0x0, 
>     background_area=0x0, background_area@entry=0x7fffffffd880, cell_area=0x438, cell_area@entry=0x7fffffffd890, flags=0, 
>     action=26875504, action@entry=2, focus_rectangle=0x0, editable_widget=0x7fffffffd878, event=0x16af230, path_string=0x1a1e630 "19", 
>     expose_area=<optimized out>) at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtktreeviewcolumn.c:2913
> #60 0x00007ffff79ca6ab in _gtk_tree_view_column_cell_event (tree_column=0x16a33f0, editable_widget=0x7fffffffd878, event=0x16af230, 
>     path_string=0x1a1e630 "19", background_area=0x7fffffffd880, cell_area=0x7fffffffd890, flags=0)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtktreeviewcolumn.c:3190
> #61 0x00007ffff79bf5f0 in gtk_tree_view_button_press (widget=0x1566910, event=0x16af230)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtktreeview.c:2730
> #62 0x00007ffff78c095f in _gtk_marshal_BOOLEAN__BOXED (closure=0x955e60, return_value=0x7fffffffda60, n_param_values=<optimized out>, 
>     param_values=0x7fffffffdb10, invocation_hint=<optimized out>, marshal_data=0x7ffff79beaf0 <gtk_tree_view_button_press>)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkmarshalers.c:86
> #63 0x00007ffff614f245 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #64 0x00007ffff6160e62 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> ---Type <return> to continue, or q <return> to quit---
> #65 0x00007ffff6169285 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #66 0x00007ffff61699df in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #67 0x00007ffff79d7adc in gtk_widget_event_internal (widget=widget@entry=0x1566910, event=event@entry=0x16af230)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkwidget.c:5010
> #68 0x00007ffff79d7dd1 in IA__gtk_widget_event (widget=widget@entry=0x1566910, event=event@entry=0x16af230)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkwidget.c:4807
> #69 0x00007ffff78bf0a4 in IA__gtk_propagate_event (widget=0x1566910, event=0x16af230)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkmain.c:2490
> #70 0x00007ffff78bf53b in IA__gtk_main_do_event (event=0x16af230) at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkmain.c:1685
> #71 0x00007ffff753377c in gdk_event_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>)
>     at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gdk/x11/gdkevents-x11.c:2403
> #72 0x00007ffff5e79c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #73 0x00007ffff5e79f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #74 0x00007ffff5e7a272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #75 0x00007ffff78be4b7 in IA__gtk_main () at /build/gtk+2.0-Gthrko/gtk+2.0-2.24.25/gtk/gtkmain.c:1257
> #76 0x00000000004b4796 in main (argc=1, argv=0x7fffffffe138) at ../src/main.c:1236

**Comment by elextr** [comment] 2015-02-19 21:33
Did you have any other python plugins still loaded?  There is a known problem if you unload geanypy with plugins still loaded IIRC.  And the "ghost" of the faulty plugin may still be loaded, was it visible in the Python plugin manager?

**Comment by frlan** [comment] 2015-02-19 21:37
Am 19.02.2015 um 22:33 schrieb elextr:
> Did you have any other python plugins still loaded? There is a known
> problem if you unload geanypy with plugins still loaded IIRC. And the
> "ghost" of the faulty plugin may still be loaded, was it visible in the
> Python plugin manager?


2x yes.

**Comment by elextr** [comment] 2015-02-19 22:24
Looks like a duplicate of #12 then.

**Comment by codebrainz** [comment] 2015-02-20 01:14
Hehe, the GDB traceback in the description "referenced" basically every Issue here :)

Maybe code tags instead of blockquote would prevent?

**Comment by codebrainz** [comment] 2015-02-20 01:23
I'm gonna close this to keep it all together into one Issue for #12, it will leave the details for reference I think. @frlan thanks for reporting and giving traceback.

**Closed by codebrainz** 2015-02-20 01:23 UTC
Labels: duplicate
